import { createSlice } from "@reduxjs/toolkit"; // Import createSlice from Redux Toolkit
import { getPokeData } from "./pokeAction"; // Import the async thunk getPokeData from pokeAction

// Initial state for the slice
const initState = {
    poke: [] // Array to hold fetched Pokemon data
};

// Create a slice for managing Pokemon-related state
export const pokeSlice = createSlice({
    name: "poke", // Name of the slice
    initialState: initState, // Initial state
    reducers: {}, // No additional reducers defined
    extraReducers: builder => {
        // Define extra reducers for handling async actions
        builder.addCase(getPokeData.fulfilled, (state, action) => {
            // Handle fulfilled action from getPokeData async thunk
            state.poke = action.payload; // Update the poke state with the fetched data
        });
    }
});

export default pokeSlice.reducer; // Export the reducer function generated by createSlice
